# Generated by Django 2.2.7 on 2019-11-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghostpost',
            name='badvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ghostpost',
            name='goodvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ghostpost',
            name='totalvotes',
            field=models.IntegerField(default=0),
        ),
    ]
